name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test-fmt:
    name: Lint, Test, and Format Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [lint, test, fmt]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Lint Code
        if: matrix.job == 'lint'
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run Tests
        if: matrix.job == 'test'
        run: cargo test --all-features --all-targets

      - name: Check Code Formatting
        if: matrix.job == 'fmt'
        run: cargo fmt --all -- --check
